{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9fa09fa3-c753-4c9e-80b8-f9ee7fb741de",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "def load_model():\n",
    "    with open('saved_steps.pkl', 'rb') as file:\n",
    "        data = pickle.load(file)\n",
    "    return data\n",
    "\n",
    "data = load_model()\n",
    "\n",
    "regressor = data[\"model\"]\n",
    "le_country = data[\"le_country\"]\n",
    "le_education = data[\"le_education\"]\n",
    "\n",
    "def show_predict_page():\n",
    "    st.title(\"Software Developer Salary Prediction\")\n",
    "\n",
    "    st.write(\"\"\"### We need some information to predict the salary\"\"\")\n",
    "\n",
    "    countries = (\n",
    "        \"United States of America\",\n",
    "        \"India\",\n",
    "        \"United Kingdom of Great Britain and Northern Ireland\",\n",
    "        \"Germany\",\n",
    "        \"Canada\",\n",
    "        \"Brazil\",\n",
    "        \"France\",\n",
    "        \"Spain\",\n",
    "        \"Australia\",\n",
    "        \"Netherlands\",\n",
    "        \"Poland\",\n",
    "        \"Italy\",\n",
    "        \"Russian Federation\",\n",
    "        \"Sweden\",\n",
    "        \"Switzerland\",\n",
    "        \"Austria\",\n",
    "        \"Denmark\",\n",
    "        \"Czech Republic\",\n",
    "        \"Norway\",\n",
    "        \"Portugal\",\n",
    "        \"Israel\",\n",
    "        \"Belgium\",\n",
    "        \"Finland\",\n",
    "        \"Ukraine\",\n",
    "        \"New Zealand\",\n",
    "        \"Romania\",\n",
    "        \n",
    "        \n",
    "    )\n",
    "\n",
    "    education = (\n",
    "        \"Less than a Bachelors\",\n",
    "        \"Bachelor’s degree\",\n",
    "        \"Master’s degree\",\n",
    "        \"Post grad\",\n",
    "    )\n",
    "\n",
    "    country = st.selectbox(\"Country\", countries)\n",
    "    education = st.selectbox(\"Education Level\", education)\n",
    "\n",
    "    expericence = st.slider(\"Years of Experience\", 0, 50, 3)\n",
    "\n",
    "    ok = st.button(\"Calculate Salary\")\n",
    "    if ok:\n",
    "        X = np.array([[country, education, expericence ]])\n",
    "        X[:, 0] = le_country.transform(X[:,0])\n",
    "        X[:, 1] = le_education.transform(X[:,1])\n",
    "        X = X.astype(float)\n",
    "\n",
    "        salary = regressor.predict(X)\n",
    "        st.subheader(f\"The estimated salary is ${salary[0]:.2f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a37fe3b1-8a5e-4c15-8c92-fe2d7b52d807",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
